### ISSUE TITLE
Deploy command with a deployment project fails if `.aws-dotnet-deploy` directory has not already been created

### ISSUE THREAD

**Issue by jshoemaker** [aws/aws-dotnet-deploy#420]
**Describe the bug**
I'm not sure if this will happen in other scenarios but in my case I was trying to setup a github action to run the deploy command with a deployment project that was included in the repo. The deploy command fails when checking the CDK npm package version. After digging into it a bit I found it was trying to run the npx command in the [DeployToolWorkspaceDirectoryRoot](https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.Constants/CDK.cs#L14) directory and manually creating this directory (`/home/runner/.aws-dotnet-deploy` in my case) before running the deploy command resolves the problem.

I was also able to reproduce this on my development machine (windows 10) by deleting/renaming the `.aws-dotnet-deploy` directory from my windows user directory before running the deploy command which was previously working.

**To Reproduce**
1. Ensure `.aws-dotnet-deploy` directory does not exist
2. Run `dotnet aws deploy` for a project that is setup to use a generated deployment project

**Logs**
```
Initiating deployment: Deployment project for Web to Amazon Elastic Container Service
Configuring AWS Cloud Development Kit (CDK)...

Failed to execute npx --no-install cdk --version
```

**Expected behavior**
The `.aws-dotnet-deploy` directory should be created by the tool if it is missing

**Environment (please complete the following information):**
 - CLI Version: 0.31.11+49dde02079
 - OS Info: Windows 10, Ubuntu

**Additional context**
The definition for my github action that was failing
```
name: Deploy to AWS
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Head
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Install AWS .NET Deployment Tool
        run: dotnet tool install -g AWS.Deploy.CLI

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Execute Deployment
        working-directory: ./Web
        run: dotnet aws deploy --silent --deployment-project ../Web.Deployment/ --apply ../deployment-settings.json
```

---

This is a :bug: bug report
